display:
  displayNum: 0
  height: 800
  screenNum: 0
  virtualDisplays:
  - id: vdisp
    viewport:
    - [0, 0]
    - [1280, 0]
    - [1280, 800]
    - [0, 800]
  width: 1280
  windowDecoration: false
  x: 1600 # For 2nd screen (beamer)
  y: 0
geom:
  axis: {x: 0.0, y: 0.0, z: 0.1}  #This is the height of my bars actually.
  base: {x: 0.0, y: 0.0, z: 0.0}
  model: cylinder
  radius: 0.07
gamma: 1.0
red_max: false
tethered_mode: false
p2g: $(find flyvr)/monitor.exr
stimulus_plugins:
  - {path: $(find flyvr)/lib, name: StimulusFishVRTest}
  - {path: $(find flyvr)/lib, name: StimulusCylinderGrating}
  - {path: $(find flyvr)/lib, name: StimulusStarField}
  - {path: $(find flyvr)/lib, name: StimulusAltitudeEdge}
  - {path: $(find flyvr)/lib, name: StimulusSphere}
  - {path: $(find flyvr)/lib, name: StimulusOSG}
  - {path: $(find flyvr)/lib, name: StimulusCylinderGrating_centered}
  - {path: $(find flyvr)/lib, name: StimulusCylinderGrating_centered_bw}
  - {path: $(find flyvr)/lib, name: StimulusCylinderGrating_centered_bw_pulsed}
